import type { Tutor } from "./index";

export const initialTutorData: Tutor[] = [
  {
    id: "T-001",
    nombre: "María",
    apellido: "González",
    cedula: "001-1234567-8",
    email: "maria.gonzalez@empresa.com",
    telefono: "809-567-8901",
    departamento: "Desarrollo",
    centroTrabajo: "Tech Solutions S.A.",
    status: "active",
  },
  {
    id: "T-002",
    nombre: "Juan",
    apellido: "Rodríguez",
    cedula: "001-8765432-1",
    email: "juan.rodriguez@industria.com",
    telefono: "829-567-8902",
    departamento: "Operaciones",
    centroTrabajo: "Industrias Nacionales",
    status: "active",
  },
  {
    id: "T-003",
    nombre: "Ana",
    apellido: "Martínez",
    cedula: "402-2345678-9",
    email: "ana.martinez@agencia.com",
    telefono: "849-567-8903",
    departamento: "Diseño Gráfico",
    centroTrabajo: "Agencia Creativa M&A",
    status: "pending",
  },
  {
    id: "T-004",
    nombre: "Carlos",
    apellido: "López",
    cedula: "001-9999999-9",
    email: "carlos.lopez@fintech.com",
    telefono: "809-567-8904",
    departamento: "Seguridad TI",
    centroTrabajo: "Finanzas Digitales Corp",
    status: "pending",
  },
  {
    id: "T-005",
    nombre: "Laura",
    apellido: "Sánchez",
    cedula: "031-1111111-1",
    email: "laura.sanchez@ejemplo.com",
    telefono: "829-567-8905",
    departamento: "Supply Chain",
    centroTrabajo: "Logística Express",
    status: "deleted",
    deletedAt: "2024-06-01",
  },
  {
    id: "T-006",
    nombre: "Roberto",
    apellido: "Díaz",
    cedula: "001-2222222-2",
    email: "roberto.diaz@ejemplo.com",
    telefono: "849-567-8906",
    departamento: "Mantenimiento Preventivo",
    centroTrabajo: "Ensambladora del Norte",
    status: "deleted",
    deletedAt: "2024-07-01",
  },
];
