import type { Tutor } from "./index";

export const initialTutorData: Tutor[] = [
  {
    id: "T-001",
    nombre: "María",
    apellido: "González",
    email: "maria.gonzalez@empresa.com",
    telefono: "+1 234-567-8901",
    cargo: "Ingeniero de Software Senior",
    departamento: "Desarrollo",
    centroTrabajo: "Tech Solutions S.A.",
    status: "active",
  },
  {
    id: "T-002",
    nombre: "Juan",
    apellido: "Rodríguez",
    email: "juan.rodriguez@industria.com",
    telefono: "+1 234-567-8902",
    cargo: "Jefe de Mantenimiento",
    departamento: "Operaciones",
    centroTrabajo: "Industrias Nacionales",
    status: "active",
  },
  {
    id: "T-003",
    nombre: "Ana",
    apellido: "Martínez",
    email: "ana.martinez@agencia.com",
    telefono: "+1 234-567-8903",
    cargo: "Directora de Arte",
    departamento: "Diseño Gráfico",
    centroTrabajo: "Agencia Creativa M&A",
    status: "pending",
  },
  {
    id: "T-004",
    nombre: "Carlos",
    apellido: "López",
    email: "carlos.lopez@fintech.com",
    telefono: "+1 234-567-8904",
    cargo: "Especialista en Ciberseguridad",
    departamento: "Seguridad TI",
    centroTrabajo: "Finanzas Digitales Corp",
    status: "pending",
  },
  {
    id: "T-005",
    nombre: "Laura",
    apellido: "Sánchez",
    email: "laura.sanchez@ejemplo.com",
    telefono: "+1 234-567-8905",
    cargo: "Coordinadora Logística",
    departamento: "Supply Chain",
    centroTrabajo: "Logística Express",
    status: "deleted",
    deletedAt: "2024-06-01",
  },
  {
    id: "T-006",
    nombre: "Roberto",
    apellido: "Díaz",
    email: "roberto.diaz@ejemplo.com",
    telefono: "+1 234-567-8906",
    cargo: "Ingeniero Mecánico",
    departamento: "Mantenimiento Preventivo",
    centroTrabajo: "Ensambladora del Norte",
    status: "deleted",
    deletedAt: "2024-07-01",
  },
];
