import type { Tutor } from "./index";

export const initialTutorData: Tutor[] = [
  {
    id: "T-001",
    nombre: "María",
    apellido: "González",
    cedula: "001-1234567-8",
    email: "maria.gonzalez@empresa.com",
    telefono: "809-567-8901",
    departamento: "Desarrollo",
    nombreCentroTrabajo: "Tech Solutions S.A.",
    idCentroTrabajo: "CT-1024",
    estado: "activo",
    fechaCreacion: "2024-01-10",
  },
  {
    id: "T-002",
    nombre: "Juan",
    apellido: "Rodríguez",
    cedula: "001-8765432-1",
    email: "juan.rodriguez@industria.com",
    telefono: "829-567-8902",
    departamento: "Operaciones",
    nombreCentroTrabajo: "Industrias Nacionales",
    idCentroTrabajo: "CT-002",
    estado: "activo",
    fechaCreacion: "2024-02-15",
  },
  {
    id: "T-003",
    nombre: "Ana",
    apellido: "Martínez",
    cedula: "402-2345678-9",
    email: "ana.martinez@agencia.com",
    telefono: "849-567-8903",
    departamento: "Diseño Gráfico",
    nombreCentroTrabajo: "Agencia Creativa M&A",
    idCentroTrabajo: "CT-003",
    estado: "inactivo",
    fechaCreacion: "2024-03-20",
  },
];
