import type { EvaluacionForm } from "../types";

export const EMPTY_FORM: EvaluacionForm = {
  identidadTitulo: "",
  codigoTitulo: "",
  nombreApellidos: "",
  horario: "",
  direccion: "",
  telefonos: "",
  fechaInicioPasantia: "",
  fechaTerminoPasantia: "",
  centroTrabajo: "",
  direccionEmpresa: "",
  telefonosEmpresa: "",
  personaContacto: "",
  nombreTutor: "",
  telefonosCorreoTutor: "",
  conocimientosTeoricos: Array(14).fill(""),
  asimilacionInstruccionesVerbales: Array(14).fill(""),
  asimilacionInstruccionesEscritas: Array(14).fill(""),
  asimilacionInstruccionesSimbolicas: Array(14).fill(""),
  subtotalCapacidad: Array(14).fill(""),
  organizacionPlanificacion: Array(14).fill(""),
  metodo: Array(14).fill(""),
  ritmoTrabajo: Array(14).fill(""),
  trabajoRealizado: Array(14).fill(""),
  subtotalHabilidad: Array(14).fill(""),
  iniciativa: Array(14).fill(""),
  trabajoEquipo: Array(14).fill(""),
  puntualidadAsistencia: Array(14).fill(""),
  responsabilidad: Array(14).fill(""),
  subtotalActitud: Array(14).fill(""),
  total: Array(14).fill(""),
  promedioCapacidades: "",
  promedioHabilidades: "",
  promedioActitudes: "",
  notaFinal: "",
  observaciones: "",
  raContenido: "",
  criterio1: "",
  criterio2: "",
  criterio3: "",
  criterio4: "",
  criterio5: "",
  criterio6: "",
};
