import type { Tutor } from "./index";

export const initialTutorData: Tutor[] = [
  {
    id: "TA-001",
    nombre: "María",
    apellido: "González",
    email: "maria.gonzalez@ipisa.edu.do",
    telefono: "+1 809-567-8901",
    especialidadTecnica: "Redes y Comunicaciones",
    areaAsignada: "Informática",
    status: "active",
    fechaContratacion: "2024-01-15",
  },
  {
    id: "TA-002",
    nombre: "Juan",
    apellido: "Rodríguez",
    email: "juan.rodriguez@ipisa.edu.do",
    telefono: "+1 809-567-8902",
    especialidadTecnica: "Electricidad Industrial",
    areaAsignada: "Talleres",
    status: "active",
    fechaContratacion: "2024-02-20",
  },
  {
    id: "TA-003",
    nombre: "Ana",
    apellido: "Martínez",
    email: "ana.martinez@ipisa.edu.do",
    telefono: "+1 809-567-8903",
    especialidadTecnica: "Mecánica Automotriz",
    areaAsignada: "Talleres",
    status: "pending",
    fechaContratacion: "2024-03-10",
  },
  {
    id: "TA-004",
    nombre: "Carlos",
    apellido: "López",
    email: "carlos.lopez@ipisa.edu.do",
    telefono: "+1 809-567-8904",
    especialidadTecnica: "Matemáticas Aplicadas",
    areaAsignada: "Académica",
    status: "pending",
    fechaContratacion: "2024-04-05",
  },
  {
    id: "TA-005",
    nombre: "Laura",
    apellido: "Sánchez",
    email: "laura.sanchez@ipisa.edu.do",
    telefono: "+1 809-567-8905",
    especialidadTecnica: "Electrónica",
    areaAsignada: "Talleres",
    status: "deleted",
    fechaContratacion: "2024-05-12",
    deletedAt: "2024-06-01",
  },
];
